name: server_monitor
description: Server monitoring application

publish_to: 'none'

version: 0.0.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  uni_links: ^0.4.0
  dio: ^4.0.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  charts_flutter: ^0.10.0
  provider: ^5.0.0
  syncfusion_flutter_charts: ^19.1.55+1
  shared_preferences: ^2.0.5
  build_runner: ^1.12.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+2
  flutter_launcher_icons: ^0.9.0

flutter:
  assets:
    - assets/icons/server_icon.png
  uses-material-design: true

flutter_icons:
    android: true
    image_path: server_icon.png
