name: server_monitor
description: Server monitoring application

publish_to: 'none'

version: 0.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.8.0
  uni_links: ^0.4.0
  dio: ^3.0.10
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  charts_flutter: ^0.9.0
  provider: ^4.3.2+3
  syncfusion_flutter_charts: ^18.4.30

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+12
  build_runner: ^1.10.2

flutter:
  assets:
    - assets/icons/server_icon.png
  uses-material-design: true

flutter_icons:
    android: true
    image_path: server_icon.png
